<?php
/**
 * Email
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PaperBoy\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PaperBoy HTTP API
 *
 * Tenant-bound transactional email API. API keys select one organization and one live or test environment. Stored instants and HTTP timestamps are RFC 3339 UTC. The queue is provider-neutral: self-hosted SMTP and Cloudflare Email Service and Amazon SES use the same messages, limits, suppressions, and event model. The signed-in console renders this contract at `/app/docs`. The Rust CLI in `crates/paperboy` calls the same bearer-key routes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PaperBoy\OpenApi\Model;

use \ArrayAccess;
use \PaperBoy\OpenApi\ObjectSerializer;

/**
 * Email Class Doc Comment
 *
 * @category Class
 * @package  PaperBoy\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Email implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Email';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'attachments' => '\PaperBoy\OpenApi\Model\StoredAttachment[]',
        'attempt_count' => 'int',
        'created_at' => '\DateTime',
        'delivery_mode' => 'string',
        'domain_id' => 'string',
        'environment' => 'string',
        'failed_at' => 'mixed',
        'failure_reason' => 'string',
        'from' => 'string',
        'html' => 'string',
        'id' => 'string',
        'last_attempt_at' => 'mixed',
        'last_error_code' => 'string',
        'next_attempt_at' => 'mixed',
        'object' => 'string',
        'open_tracking_enabled' => 'bool',
        'provider' => '\PaperBoy\OpenApi\Model\MessageOutboundProvider',
        'sent_at' => 'mixed',
        'status' => 'string',
        'subject' => 'string',
        'tags' => '\PaperBoy\OpenApi\Model\EmailTag[]',
        'text' => 'string',
        'to' => 'string[]',
        'updated_at' => '\DateTime'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'attachments' => null,
        'attempt_count' => null,
        'created_at' => 'date-time',
        'delivery_mode' => null,
        'domain_id' => 'uuid',
        'environment' => null,
        'failed_at' => null,
        'failure_reason' => null,
        'from' => null,
        'html' => null,
        'id' => 'uuid',
        'last_attempt_at' => null,
        'last_error_code' => null,
        'next_attempt_at' => null,
        'object' => null,
        'open_tracking_enabled' => null,
        'provider' => null,
        'sent_at' => null,
        'status' => null,
        'subject' => null,
        'tags' => null,
        'text' => null,
        'to' => null,
        'updated_at' => 'date-time'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'attachments' => false,
        'attempt_count' => false,
        'created_at' => false,
        'delivery_mode' => false,
        'domain_id' => true,
        'environment' => false,
        'failed_at' => true,
        'failure_reason' => true,
        'from' => false,
        'html' => true,
        'id' => false,
        'last_attempt_at' => true,
        'last_error_code' => true,
        'next_attempt_at' => true,
        'object' => false,
        'open_tracking_enabled' => false,
        'provider' => false,
        'sent_at' => true,
        'status' => false,
        'subject' => false,
        'tags' => false,
        'text' => true,
        'to' => false,
        'updated_at' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'attachments' => 'attachments',
        'attempt_count' => 'attempt_count',
        'created_at' => 'created_at',
        'delivery_mode' => 'delivery_mode',
        'domain_id' => 'domain_id',
        'environment' => 'environment',
        'failed_at' => 'failed_at',
        'failure_reason' => 'failure_reason',
        'from' => 'from',
        'html' => 'html',
        'id' => 'id',
        'last_attempt_at' => 'last_attempt_at',
        'last_error_code' => 'last_error_code',
        'next_attempt_at' => 'next_attempt_at',
        'object' => 'object',
        'open_tracking_enabled' => 'open_tracking_enabled',
        'provider' => 'provider',
        'sent_at' => 'sent_at',
        'status' => 'status',
        'subject' => 'subject',
        'tags' => 'tags',
        'text' => 'text',
        'to' => 'to',
        'updated_at' => 'updated_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'attachments' => 'setAttachments',
        'attempt_count' => 'setAttemptCount',
        'created_at' => 'setCreatedAt',
        'delivery_mode' => 'setDeliveryMode',
        'domain_id' => 'setDomainId',
        'environment' => 'setEnvironment',
        'failed_at' => 'setFailedAt',
        'failure_reason' => 'setFailureReason',
        'from' => 'setFrom',
        'html' => 'setHtml',
        'id' => 'setId',
        'last_attempt_at' => 'setLastAttemptAt',
        'last_error_code' => 'setLastErrorCode',
        'next_attempt_at' => 'setNextAttemptAt',
        'object' => 'setObject',
        'open_tracking_enabled' => 'setOpenTrackingEnabled',
        'provider' => 'setProvider',
        'sent_at' => 'setSentAt',
        'status' => 'setStatus',
        'subject' => 'setSubject',
        'tags' => 'setTags',
        'text' => 'setText',
        'to' => 'setTo',
        'updated_at' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'attachments' => 'getAttachments',
        'attempt_count' => 'getAttemptCount',
        'created_at' => 'getCreatedAt',
        'delivery_mode' => 'getDeliveryMode',
        'domain_id' => 'getDomainId',
        'environment' => 'getEnvironment',
        'failed_at' => 'getFailedAt',
        'failure_reason' => 'getFailureReason',
        'from' => 'getFrom',
        'html' => 'getHtml',
        'id' => 'getId',
        'last_attempt_at' => 'getLastAttemptAt',
        'last_error_code' => 'getLastErrorCode',
        'next_attempt_at' => 'getNextAttemptAt',
        'object' => 'getObject',
        'open_tracking_enabled' => 'getOpenTrackingEnabled',
        'provider' => 'getProvider',
        'sent_at' => 'getSentAt',
        'status' => 'getStatus',
        'subject' => 'getSubject',
        'tags' => 'getTags',
        'text' => 'getText',
        'to' => 'getTo',
        'updated_at' => 'getUpdatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const DELIVERY_MODE_LIVE = 'live';
    public const DELIVERY_MODE_TEST_SINK = 'test-sink';
    public const ENVIRONMENT_LIVE = 'live';
    public const ENVIRONMENT_TEST = 'test';
    public const OBJECT_EMAIL = 'email';
    public const STATUS_QUEUED = 'queued';
    public const STATUS_SENDING = 'sending';
    public const STATUS_SENT = 'sent';
    public const STATUS_FAILED = 'failed';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDeliveryModeAllowableValues()
    {
        return [
            self::DELIVERY_MODE_LIVE,
            self::DELIVERY_MODE_TEST_SINK,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEnvironmentAllowableValues()
    {
        return [
            self::ENVIRONMENT_LIVE,
            self::ENVIRONMENT_TEST,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getObjectAllowableValues()
    {
        return [
            self::OBJECT_EMAIL,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_QUEUED,
            self::STATUS_SENDING,
            self::STATUS_SENT,
            self::STATUS_FAILED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('attachments', $data ?? [], null);
        $this->setIfExists('attempt_count', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('delivery_mode', $data ?? [], null);
        $this->setIfExists('domain_id', $data ?? [], null);
        $this->setIfExists('environment', $data ?? [], null);
        $this->setIfExists('failed_at', $data ?? [], null);
        $this->setIfExists('failure_reason', $data ?? [], null);
        $this->setIfExists('from', $data ?? [], null);
        $this->setIfExists('html', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('last_attempt_at', $data ?? [], null);
        $this->setIfExists('last_error_code', $data ?? [], null);
        $this->setIfExists('next_attempt_at', $data ?? [], null);
        $this->setIfExists('object', $data ?? [], null);
        $this->setIfExists('open_tracking_enabled', $data ?? [], null);
        $this->setIfExists('provider', $data ?? [], null);
        $this->setIfExists('sent_at', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('subject', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
        $this->setIfExists('text', $data ?? [], null);
        $this->setIfExists('to', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['attachments'] === null) {
            $invalidProperties[] = "'attachments' can't be null";
        }
        if ($this->container['attempt_count'] === null) {
            $invalidProperties[] = "'attempt_count' can't be null";
        }
        if (($this->container['attempt_count'] < 0)) {
            $invalidProperties[] = "invalid value for 'attempt_count', must be bigger than or equal to 0.";
        }

        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['delivery_mode'] === null) {
            $invalidProperties[] = "'delivery_mode' can't be null";
        }
        $allowedValues = $this->getDeliveryModeAllowableValues();
        if (!is_null($this->container['delivery_mode']) && !in_array($this->container['delivery_mode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'delivery_mode', must be one of '%s'",
                $this->container['delivery_mode'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['domain_id'] === null && !$this->isNullableSetToNull('domain_id')) {
            $invalidProperties[] = "'domain_id' is required";
        }
        if ($this->container['environment'] === null) {
            $invalidProperties[] = "'environment' can't be null";
        }
        $allowedValues = $this->getEnvironmentAllowableValues();
        if (!is_null($this->container['environment']) && !in_array($this->container['environment'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'environment', must be one of '%s'",
                $this->container['environment'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['failed_at'] === null && !$this->isNullableSetToNull('failed_at')) {
            $invalidProperties[] = "'failed_at' is required";
        }
        if ($this->container['failure_reason'] === null && !$this->isNullableSetToNull('failure_reason')) {
            $invalidProperties[] = "'failure_reason' is required";
        }
        if ($this->container['from'] === null) {
            $invalidProperties[] = "'from' can't be null";
        }
        if ($this->container['html'] === null && !$this->isNullableSetToNull('html')) {
            $invalidProperties[] = "'html' is required";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['last_attempt_at'] === null && !$this->isNullableSetToNull('last_attempt_at')) {
            $invalidProperties[] = "'last_attempt_at' is required";
        }
        if ($this->container['last_error_code'] === null && !$this->isNullableSetToNull('last_error_code')) {
            $invalidProperties[] = "'last_error_code' is required";
        }
        if ($this->container['next_attempt_at'] === null && !$this->isNullableSetToNull('next_attempt_at')) {
            $invalidProperties[] = "'next_attempt_at' is required";
        }
        if ($this->container['object'] === null) {
            $invalidProperties[] = "'object' can't be null";
        }
        $allowedValues = $this->getObjectAllowableValues();
        if (!is_null($this->container['object']) && !in_array($this->container['object'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'object', must be one of '%s'",
                $this->container['object'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['open_tracking_enabled'] === null) {
            $invalidProperties[] = "'open_tracking_enabled' can't be null";
        }
        if ($this->container['provider'] === null) {
            $invalidProperties[] = "'provider' can't be null";
        }
        if ($this->container['sent_at'] === null && !$this->isNullableSetToNull('sent_at')) {
            $invalidProperties[] = "'sent_at' is required";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['subject'] === null) {
            $invalidProperties[] = "'subject' can't be null";
        }
        if ($this->container['tags'] === null) {
            $invalidProperties[] = "'tags' can't be null";
        }
        if ((count($this->container['tags']) > 75)) {
            $invalidProperties[] = "invalid value for 'tags', number of items must be less than or equal to 75.";
        }

        if ($this->container['text'] === null && !$this->isNullableSetToNull('text')) {
            $invalidProperties[] = "'text' is required";
        }
        if ($this->container['to'] === null) {
            $invalidProperties[] = "'to' can't be null";
        }
        if ($this->container['updated_at'] === null) {
            $invalidProperties[] = "'updated_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets attachments
     *
     * @return \PaperBoy\OpenApi\Model\StoredAttachment[]
     */
    public function getAttachments()
    {
        return $this->container['attachments'];
    }

    /**
     * Sets attachments
     *
     * @param \PaperBoy\OpenApi\Model\StoredAttachment[] $attachments attachments
     *
     * @return self
     */
    public function setAttachments($attachments)
    {
        if (is_null($attachments)) {
            throw new \InvalidArgumentException('non-nullable attachments cannot be null');
        }
        $this->container['attachments'] = $attachments;

        return $this;
    }

    /**
     * Gets attempt_count
     *
     * @return int
     */
    public function getAttemptCount()
    {
        return $this->container['attempt_count'];
    }

    /**
     * Sets attempt_count
     *
     * @param int $attempt_count attempt_count
     *
     * @return self
     */
    public function setAttemptCount($attempt_count)
    {
        if (is_null($attempt_count)) {
            throw new \InvalidArgumentException('non-nullable attempt_count cannot be null');
        }
        if (($attempt_count < 0)) {
            throw new \InvalidArgumentException('invalid value for $attempt_count when calling Email., must be bigger than or equal to 0.');
        }

        $this->container['attempt_count'] = $attempt_count;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at RFC 3339 UTC instant. PaperBoy serializes this with a trailing `Z`.
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets delivery_mode
     *
     * @return string
     */
    public function getDeliveryMode()
    {
        return $this->container['delivery_mode'];
    }

    /**
     * Sets delivery_mode
     *
     * @param string $delivery_mode delivery_mode
     *
     * @return self
     */
    public function setDeliveryMode($delivery_mode)
    {
        if (is_null($delivery_mode)) {
            throw new \InvalidArgumentException('non-nullable delivery_mode cannot be null');
        }
        $allowedValues = $this->getDeliveryModeAllowableValues();
        if (!in_array($delivery_mode, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'delivery_mode', must be one of '%s'",
                    $delivery_mode,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['delivery_mode'] = $delivery_mode;

        return $this;
    }

    /**
     * Gets domain_id
     *
     * @return string|null
     */
    public function getDomainId()
    {
        return $this->container['domain_id'];
    }

    /**
     * Sets domain_id
     *
     * @param string|null $domain_id domain_id
     *
     * @return self
     */
    public function setDomainId($domain_id)
    {
        if (is_null($domain_id)) {
            array_push($this->openAPINullablesSetToNull, 'domain_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('domain_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['domain_id'] = $domain_id;

        return $this;
    }

    /**
     * Gets environment
     *
     * @return string
     */
    public function getEnvironment()
    {
        return $this->container['environment'];
    }

    /**
     * Sets environment
     *
     * @param string $environment environment
     *
     * @return self
     */
    public function setEnvironment($environment)
    {
        if (is_null($environment)) {
            throw new \InvalidArgumentException('non-nullable environment cannot be null');
        }
        $allowedValues = $this->getEnvironmentAllowableValues();
        if (!in_array($environment, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'environment', must be one of '%s'",
                    $environment,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['environment'] = $environment;

        return $this;
    }

    /**
     * Gets failed_at
     *
     * @return mixed|null
     */
    public function getFailedAt()
    {
        return $this->container['failed_at'];
    }

    /**
     * Sets failed_at
     *
     * @param mixed|null $failed_at failed_at
     *
     * @return self
     */
    public function setFailedAt($failed_at)
    {
        if (is_null($failed_at)) {
            array_push($this->openAPINullablesSetToNull, 'failed_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('failed_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['failed_at'] = $failed_at;

        return $this;
    }

    /**
     * Gets failure_reason
     *
     * @return string|null
     */
    public function getFailureReason()
    {
        return $this->container['failure_reason'];
    }

    /**
     * Sets failure_reason
     *
     * @param string|null $failure_reason failure_reason
     *
     * @return self
     */
    public function setFailureReason($failure_reason)
    {
        if (is_null($failure_reason)) {
            array_push($this->openAPINullablesSetToNull, 'failure_reason');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('failure_reason', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['failure_reason'] = $failure_reason;

        return $this;
    }

    /**
     * Gets from
     *
     * @return string
     */
    public function getFrom()
    {
        return $this->container['from'];
    }

    /**
     * Sets from
     *
     * @param string $from from
     *
     * @return self
     */
    public function setFrom($from)
    {
        if (is_null($from)) {
            throw new \InvalidArgumentException('non-nullable from cannot be null');
        }
        $this->container['from'] = $from;

        return $this;
    }

    /**
     * Gets html
     *
     * @return string|null
     */
    public function getHtml()
    {
        return $this->container['html'];
    }

    /**
     * Sets html
     *
     * @param string|null $html html
     *
     * @return self
     */
    public function setHtml($html)
    {
        if (is_null($html)) {
            array_push($this->openAPINullablesSetToNull, 'html');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('html', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['html'] = $html;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets last_attempt_at
     *
     * @return mixed|null
     */
    public function getLastAttemptAt()
    {
        return $this->container['last_attempt_at'];
    }

    /**
     * Sets last_attempt_at
     *
     * @param mixed|null $last_attempt_at last_attempt_at
     *
     * @return self
     */
    public function setLastAttemptAt($last_attempt_at)
    {
        if (is_null($last_attempt_at)) {
            array_push($this->openAPINullablesSetToNull, 'last_attempt_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_attempt_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_attempt_at'] = $last_attempt_at;

        return $this;
    }

    /**
     * Gets last_error_code
     *
     * @return string|null
     */
    public function getLastErrorCode()
    {
        return $this->container['last_error_code'];
    }

    /**
     * Sets last_error_code
     *
     * @param string|null $last_error_code last_error_code
     *
     * @return self
     */
    public function setLastErrorCode($last_error_code)
    {
        if (is_null($last_error_code)) {
            array_push($this->openAPINullablesSetToNull, 'last_error_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_error_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_error_code'] = $last_error_code;

        return $this;
    }

    /**
     * Gets next_attempt_at
     *
     * @return mixed|null
     */
    public function getNextAttemptAt()
    {
        return $this->container['next_attempt_at'];
    }

    /**
     * Sets next_attempt_at
     *
     * @param mixed|null $next_attempt_at next_attempt_at
     *
     * @return self
     */
    public function setNextAttemptAt($next_attempt_at)
    {
        if (is_null($next_attempt_at)) {
            array_push($this->openAPINullablesSetToNull, 'next_attempt_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('next_attempt_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['next_attempt_at'] = $next_attempt_at;

        return $this;
    }

    /**
     * Gets object
     *
     * @return string
     */
    public function getObject()
    {
        return $this->container['object'];
    }

    /**
     * Sets object
     *
     * @param string $object object
     *
     * @return self
     */
    public function setObject($object)
    {
        if (is_null($object)) {
            throw new \InvalidArgumentException('non-nullable object cannot be null');
        }
        $allowedValues = $this->getObjectAllowableValues();
        if (!in_array($object, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'object', must be one of '%s'",
                    $object,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['object'] = $object;

        return $this;
    }

    /**
     * Gets open_tracking_enabled
     *
     * @return bool
     */
    public function getOpenTrackingEnabled()
    {
        return $this->container['open_tracking_enabled'];
    }

    /**
     * Sets open_tracking_enabled
     *
     * @param bool $open_tracking_enabled open_tracking_enabled
     *
     * @return self
     */
    public function setOpenTrackingEnabled($open_tracking_enabled)
    {
        if (is_null($open_tracking_enabled)) {
            throw new \InvalidArgumentException('non-nullable open_tracking_enabled cannot be null');
        }
        $this->container['open_tracking_enabled'] = $open_tracking_enabled;

        return $this;
    }

    /**
     * Gets provider
     *
     * @return \PaperBoy\OpenApi\Model\MessageOutboundProvider
     */
    public function getProvider()
    {
        return $this->container['provider'];
    }

    /**
     * Sets provider
     *
     * @param \PaperBoy\OpenApi\Model\MessageOutboundProvider $provider provider
     *
     * @return self
     */
    public function setProvider($provider)
    {
        if (is_null($provider)) {
            throw new \InvalidArgumentException('non-nullable provider cannot be null');
        }
        $this->container['provider'] = $provider;

        return $this;
    }

    /**
     * Gets sent_at
     *
     * @return mixed|null
     */
    public function getSentAt()
    {
        return $this->container['sent_at'];
    }

    /**
     * Sets sent_at
     *
     * @param mixed|null $sent_at sent_at
     *
     * @return self
     */
    public function setSentAt($sent_at)
    {
        if (is_null($sent_at)) {
            array_push($this->openAPINullablesSetToNull, 'sent_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sent_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sent_at'] = $sent_at;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets subject
     *
     * @return string
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param string $subject subject
     *
     * @return self
     */
    public function setSubject($subject)
    {
        if (is_null($subject)) {
            throw new \InvalidArgumentException('non-nullable subject cannot be null');
        }
        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return \PaperBoy\OpenApi\Model\EmailTag[]
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param \PaperBoy\OpenApi\Model\EmailTag[] $tags tags
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }
        if ((count($tags) > 75)) {
            throw new \InvalidArgumentException('invalid value for $tags when calling Email., number of items must be less than or equal to 75.');
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets text
     *
     * @return string|null
     */
    public function getText()
    {
        return $this->container['text'];
    }

    /**
     * Sets text
     *
     * @param string|null $text text
     *
     * @return self
     */
    public function setText($text)
    {
        if (is_null($text)) {
            array_push($this->openAPINullablesSetToNull, 'text');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text'] = $text;

        return $this;
    }

    /**
     * Gets to
     *
     * @return string[]
     */
    public function getTo()
    {
        return $this->container['to'];
    }

    /**
     * Sets to
     *
     * @param string[] $to to
     *
     * @return self
     */
    public function setTo($to)
    {
        if (is_null($to)) {
            throw new \InvalidArgumentException('non-nullable to cannot be null');
        }
        $this->container['to'] = $to;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at RFC 3339 UTC instant. PaperBoy serializes this with a trailing `Z`.
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


