<?php
/**
 * InlineEmailInput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PaperBoy\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PaperBoy HTTP API
 *
 * Tenant-bound transactional email API. API keys select one organization and one live or test environment. Stored instants and HTTP timestamps are RFC 3339 UTC. The queue is provider-neutral: self-hosted SMTP and Cloudflare Email Service and Amazon SES use the same messages, limits, suppressions, and event model. The signed-in console renders this contract at `/app/docs`. The Rust CLI in `crates/paperboy` calls the same bearer-key routes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PaperBoy\OpenApi\Model;

use \ArrayAccess;
use \PaperBoy\OpenApi\ObjectSerializer;

/**
 * InlineEmailInput Class Doc Comment
 *
 * @category Class
 * @package  PaperBoy\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class InlineEmailInput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'InlineEmailInput';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'from' => 'string',
        'to' => '\PaperBoy\OpenApi\Model\Recipients',
        'subject' => 'string',
        'html' => 'string',
        'idempotency_key' => 'string',
        'text' => 'string',
        'tags' => '\PaperBoy\OpenApi\Model\EmailTag[]',
        'attachments' => '\PaperBoy\OpenApi\Model\EmailAttachment[]',
        'reply_to' => '\PaperBoy\OpenApi\Model\Recipients',
        'cc' => '\PaperBoy\OpenApi\Model\Recipients',
        'bcc' => '\PaperBoy\OpenApi\Model\Recipients',
        'headers' => 'array<string,string>',
        'scheduled_at' => '\DateTime'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'from' => null,
        'to' => null,
        'subject' => null,
        'html' => null,
        'idempotency_key' => null,
        'text' => null,
        'tags' => null,
        'attachments' => null,
        'reply_to' => null,
        'cc' => null,
        'bcc' => null,
        'headers' => null,
        'scheduled_at' => 'date-time'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'from' => false,
        'to' => false,
        'subject' => false,
        'html' => false,
        'idempotency_key' => false,
        'text' => false,
        'tags' => false,
        'attachments' => false,
        'reply_to' => false,
        'cc' => false,
        'bcc' => false,
        'headers' => false,
        'scheduled_at' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'from' => 'from',
        'to' => 'to',
        'subject' => 'subject',
        'html' => 'html',
        'idempotency_key' => 'idempotency_key',
        'text' => 'text',
        'tags' => 'tags',
        'attachments' => 'attachments',
        'reply_to' => 'reply_to',
        'cc' => 'cc',
        'bcc' => 'bcc',
        'headers' => 'headers',
        'scheduled_at' => 'scheduled_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'from' => 'setFrom',
        'to' => 'setTo',
        'subject' => 'setSubject',
        'html' => 'setHtml',
        'idempotency_key' => 'setIdempotencyKey',
        'text' => 'setText',
        'tags' => 'setTags',
        'attachments' => 'setAttachments',
        'reply_to' => 'setReplyTo',
        'cc' => 'setCc',
        'bcc' => 'setBcc',
        'headers' => 'setHeaders',
        'scheduled_at' => 'setScheduledAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'from' => 'getFrom',
        'to' => 'getTo',
        'subject' => 'getSubject',
        'html' => 'getHtml',
        'idempotency_key' => 'getIdempotencyKey',
        'text' => 'getText',
        'tags' => 'getTags',
        'attachments' => 'getAttachments',
        'reply_to' => 'getReplyTo',
        'cc' => 'getCc',
        'bcc' => 'getBcc',
        'headers' => 'getHeaders',
        'scheduled_at' => 'getScheduledAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('from', $data ?? [], null);
        $this->setIfExists('to', $data ?? [], null);
        $this->setIfExists('subject', $data ?? [], null);
        $this->setIfExists('html', $data ?? [], null);
        $this->setIfExists('idempotency_key', $data ?? [], null);
        $this->setIfExists('text', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
        $this->setIfExists('attachments', $data ?? [], null);
        $this->setIfExists('reply_to', $data ?? [], null);
        $this->setIfExists('cc', $data ?? [], null);
        $this->setIfExists('bcc', $data ?? [], null);
        $this->setIfExists('headers', $data ?? [], null);
        $this->setIfExists('scheduled_at', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['from'] === null) {
            $invalidProperties[] = "'from' can't be null";
        }
        if ((mb_strlen($this->container['from']) > 320)) {
            $invalidProperties[] = "invalid value for 'from', the character length must be smaller than or equal to 320.";
        }

        if ((mb_strlen($this->container['from']) < 3)) {
            $invalidProperties[] = "invalid value for 'from', the character length must be bigger than or equal to 3.";
        }

        if ($this->container['to'] === null) {
            $invalidProperties[] = "'to' can't be null";
        }
        if ($this->container['subject'] === null) {
            $invalidProperties[] = "'subject' can't be null";
        }
        if ((mb_strlen($this->container['subject']) > 998)) {
            $invalidProperties[] = "invalid value for 'subject', the character length must be smaller than or equal to 998.";
        }

        if ((mb_strlen($this->container['subject']) < 1)) {
            $invalidProperties[] = "invalid value for 'subject', the character length must be bigger than or equal to 1.";
        }

        if (!preg_match("/^(?=.*\\S)[^\\r\\n]*$/", $this->container['subject'])) {
            $invalidProperties[] = "invalid value for 'subject', must be conform to the pattern /^(?=.*\\S)[^\\r\\n]*$/.";
        }

        if (!is_null($this->container['html']) && (mb_strlen($this->container['html']) > 2097152)) {
            $invalidProperties[] = "invalid value for 'html', the character length must be smaller than or equal to 2097152.";
        }

        if (!is_null($this->container['idempotency_key']) && (mb_strlen($this->container['idempotency_key']) > 256)) {
            $invalidProperties[] = "invalid value for 'idempotency_key', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['idempotency_key']) && (mb_strlen($this->container['idempotency_key']) < 1)) {
            $invalidProperties[] = "invalid value for 'idempotency_key', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['idempotency_key']) && !preg_match("/^[!-~]+$/", $this->container['idempotency_key'])) {
            $invalidProperties[] = "invalid value for 'idempotency_key', must be conform to the pattern /^[!-~]+$/.";
        }

        if (!is_null($this->container['text']) && (mb_strlen($this->container['text']) > 2097152)) {
            $invalidProperties[] = "invalid value for 'text', the character length must be smaller than or equal to 2097152.";
        }

        if (!is_null($this->container['tags']) && (count($this->container['tags']) > 75)) {
            $invalidProperties[] = "invalid value for 'tags', number of items must be less than or equal to 75.";
        }

        if (!is_null($this->container['attachments']) && (count($this->container['attachments']) > 100)) {
            $invalidProperties[] = "invalid value for 'attachments', number of items must be less than or equal to 100.";
        }

        if (!is_null($this->container['headers']) && (count($this->container['headers']) > 50)) {
            $invalidProperties[] = "invalid value for 'headers', number of items must be less than or equal to 50.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets from
     *
     * @return string
     */
    public function getFrom()
    {
        return $this->container['from'];
    }

    /**
     * Sets from
     *
     * @param string $from Plain address or `Display name <address@example.com>` form.
     *
     * @return self
     */
    public function setFrom($from)
    {
        if (is_null($from)) {
            throw new \InvalidArgumentException('non-nullable from cannot be null');
        }
        if ((mb_strlen($from) > 320)) {
            throw new \InvalidArgumentException('invalid length for $from when calling InlineEmailInput., must be smaller than or equal to 320.');
        }
        if ((mb_strlen($from) < 3)) {
            throw new \InvalidArgumentException('invalid length for $from when calling InlineEmailInput., must be bigger than or equal to 3.');
        }

        $this->container['from'] = $from;

        return $this;
    }

    /**
     * Gets to
     *
     * @return \PaperBoy\OpenApi\Model\Recipients
     */
    public function getTo()
    {
        return $this->container['to'];
    }

    /**
     * Sets to
     *
     * @param \PaperBoy\OpenApi\Model\Recipients $to to
     *
     * @return self
     */
    public function setTo($to)
    {
        if (is_null($to)) {
            throw new \InvalidArgumentException('non-nullable to cannot be null');
        }
        $this->container['to'] = $to;

        return $this;
    }

    /**
     * Gets subject
     *
     * @return string
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param string $subject subject
     *
     * @return self
     */
    public function setSubject($subject)
    {
        if (is_null($subject)) {
            throw new \InvalidArgumentException('non-nullable subject cannot be null');
        }
        if ((mb_strlen($subject) > 998)) {
            throw new \InvalidArgumentException('invalid length for $subject when calling InlineEmailInput., must be smaller than or equal to 998.');
        }
        if ((mb_strlen($subject) < 1)) {
            throw new \InvalidArgumentException('invalid length for $subject when calling InlineEmailInput., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^(?=.*\\S)[^\\r\\n]*$/", ObjectSerializer::toString($subject)))) {
            throw new \InvalidArgumentException("invalid value for \$subject when calling InlineEmailInput., must conform to the pattern /^(?=.*\\S)[^\\r\\n]*$/.");
        }

        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets html
     *
     * @return string|null
     */
    public function getHtml()
    {
        return $this->container['html'];
    }

    /**
     * Sets html
     *
     * @param string|null $html html
     *
     * @return self
     */
    public function setHtml($html)
    {
        if (is_null($html)) {
            throw new \InvalidArgumentException('non-nullable html cannot be null');
        }
        if ((mb_strlen($html) > 2097152)) {
            throw new \InvalidArgumentException('invalid length for $html when calling InlineEmailInput., must be smaller than or equal to 2097152.');
        }

        $this->container['html'] = $html;

        return $this;
    }

    /**
     * Gets idempotency_key
     *
     * @return string|null
     */
    public function getIdempotencyKey()
    {
        return $this->container['idempotency_key'];
    }

    /**
     * Sets idempotency_key
     *
     * @param string|null $idempotency_key API-key-scoped key with a 24-hour lifetime measured using PostgreSQL UTC instants. A replay does not insert or resubmit a provider message.
     *
     * @return self
     */
    public function setIdempotencyKey($idempotency_key)
    {
        if (is_null($idempotency_key)) {
            throw new \InvalidArgumentException('non-nullable idempotency_key cannot be null');
        }
        if ((mb_strlen($idempotency_key) > 256)) {
            throw new \InvalidArgumentException('invalid length for $idempotency_key when calling InlineEmailInput., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($idempotency_key) < 1)) {
            throw new \InvalidArgumentException('invalid length for $idempotency_key when calling InlineEmailInput., must be bigger than or equal to 1.');
        }
        if ((!preg_match("/^[!-~]+$/", ObjectSerializer::toString($idempotency_key)))) {
            throw new \InvalidArgumentException("invalid value for \$idempotency_key when calling InlineEmailInput., must conform to the pattern /^[!-~]+$/.");
        }

        $this->container['idempotency_key'] = $idempotency_key;

        return $this;
    }

    /**
     * Gets text
     *
     * @return string|null
     */
    public function getText()
    {
        return $this->container['text'];
    }

    /**
     * Sets text
     *
     * @param string|null $text text
     *
     * @return self
     */
    public function setText($text)
    {
        if (is_null($text)) {
            throw new \InvalidArgumentException('non-nullable text cannot be null');
        }
        if ((mb_strlen($text) > 2097152)) {
            throw new \InvalidArgumentException('invalid length for $text when calling InlineEmailInput., must be smaller than or equal to 2097152.');
        }

        $this->container['text'] = $text;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return \PaperBoy\OpenApi\Model\EmailTag[]|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param \PaperBoy\OpenApi\Model\EmailTag[]|null $tags tags
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }
        if ((count($tags) > 75)) {
            throw new \InvalidArgumentException('invalid value for $tags when calling InlineEmailInput., number of items must be less than or equal to 75.');
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets attachments
     *
     * @return \PaperBoy\OpenApi\Model\EmailAttachment[]|null
     */
    public function getAttachments()
    {
        return $this->container['attachments'];
    }

    /**
     * Sets attachments
     *
     * @param \PaperBoy\OpenApi\Model\EmailAttachment[]|null $attachments Decoded bytes across all items may total at most 10 MiB.
     *
     * @return self
     */
    public function setAttachments($attachments)
    {
        if (is_null($attachments)) {
            throw new \InvalidArgumentException('non-nullable attachments cannot be null');
        }
        if ((count($attachments) > 100)) {
            throw new \InvalidArgumentException('invalid value for $attachments when calling InlineEmailInput., number of items must be less than or equal to 100.');
        }
        $this->container['attachments'] = $attachments;

        return $this;
    }

    /**
     * Gets reply_to
     *
     * @return \PaperBoy\OpenApi\Model\Recipients|null
     */
    public function getReplyTo()
    {
        return $this->container['reply_to'];
    }

    /**
     * Sets reply_to
     *
     * @param \PaperBoy\OpenApi\Model\Recipients|null $reply_to reply_to
     *
     * @return self
     */
    public function setReplyTo($reply_to)
    {
        if (is_null($reply_to)) {
            throw new \InvalidArgumentException('non-nullable reply_to cannot be null');
        }
        $this->container['reply_to'] = $reply_to;

        return $this;
    }

    /**
     * Gets cc
     *
     * @return \PaperBoy\OpenApi\Model\Recipients|null
     */
    public function getCc()
    {
        return $this->container['cc'];
    }

    /**
     * Sets cc
     *
     * @param \PaperBoy\OpenApi\Model\Recipients|null $cc cc
     *
     * @return self
     */
    public function setCc($cc)
    {
        if (is_null($cc)) {
            throw new \InvalidArgumentException('non-nullable cc cannot be null');
        }
        $this->container['cc'] = $cc;

        return $this;
    }

    /**
     * Gets bcc
     *
     * @return \PaperBoy\OpenApi\Model\Recipients|null
     */
    public function getBcc()
    {
        return $this->container['bcc'];
    }

    /**
     * Sets bcc
     *
     * @param \PaperBoy\OpenApi\Model\Recipients|null $bcc bcc
     *
     * @return self
     */
    public function setBcc($bcc)
    {
        if (is_null($bcc)) {
            throw new \InvalidArgumentException('non-nullable bcc cannot be null');
        }
        $this->container['bcc'] = $bcc;

        return $this;
    }

    /**
     * Gets headers
     *
     * @return array<string,string>|null
     */
    public function getHeaders()
    {
        return $this->container['headers'];
    }

    /**
     * Sets headers
     *
     * @param array<string,string>|null $headers Custom MIME headers. Delivery headers such as From, To, Cc, Bcc, Subject, and Date are reserved.
     *
     * @return self
     */
    public function setHeaders($headers)
    {
        if (is_null($headers)) {
            throw new \InvalidArgumentException('non-nullable headers cannot be null');
        }
        if ((count($headers) > 50)) {
            throw new \InvalidArgumentException('invalid value for $headers when calling InlineEmailInput., number of items must be less than or equal to 50.');
        }
        $this->container['headers'] = $headers;

        return $this;
    }

    /**
     * Gets scheduled_at
     *
     * @return \DateTime|null
     */
    public function getScheduledAt()
    {
        return $this->container['scheduled_at'];
    }

    /**
     * Sets scheduled_at
     *
     * @param \DateTime|null $scheduled_at ISO 8601 instant. Future values queue the message for later delivery; past values send immediately.
     *
     * @return self
     */
    public function setScheduledAt($scheduled_at)
    {
        if (is_null($scheduled_at)) {
            throw new \InvalidArgumentException('non-nullable scheduled_at cannot be null');
        }
        $this->container['scheduled_at'] = $scheduled_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


