<?php
/**
 * MessageOutboundProvider
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PaperBoy\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PaperBoy HTTP API
 *
 * Tenant-bound transactional email API. API keys select one organization and one live or test environment. Stored instants and HTTP timestamps are RFC 3339 UTC. The queue is provider-neutral: self-hosted SMTP and Cloudflare Email Service and Amazon SES use the same messages, limits, suppressions, and event model. The signed-in console renders this contract at `/app/docs`. The Rust CLI in `crates/paperboy` calls the same bearer-key routes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace PaperBoy\OpenApi\Model;
use \PaperBoy\OpenApi\ObjectSerializer;

/**
 * MessageOutboundProvider Class Doc Comment
 *
 * @category Class
 * @package  PaperBoy\OpenApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MessageOutboundProvider
{
    /**
     * Possible values of this enum
     */
    public const SMTP = 'smtp';

    public const CLOUDFLARE_EMAIL = 'cloudflare-email';

    public const AWS_SES = 'aws-ses';

    public const AZURE_EMAIL = 'azure-email';

    public const TEST_SINK = 'test-sink';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SMTP,
            self::CLOUDFLARE_EMAIL,
            self::AWS_SES,
            self::AZURE_EMAIL,
            self::TEST_SINK
        ];
    }
}


