/* tslint:disable */
/* eslint-disable */
/**
 * PaperBoy HTTP API
 * Tenant-bound transactional email API. API keys select one organization and one live or test environment. Stored instants and HTTP timestamps are RFC 3339 UTC. The queue is provider-neutral: self-hosted SMTP and Cloudflare Email Service and Amazon SES use the same messages, limits, suppressions, and event model. The signed-in console renders this contract at `/app/docs`. The Rust CLI in `crates/paperboy` calls the same bearer-key routes.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    BroadcastCreateInput,
    BroadcastEnvelope,
    BroadcastListEnvelope,
    BroadcastUpdateInput,
    ErrorEnvelope,
} from '../models/index';

export interface CancelBroadcastRequest {
    broadcastId: string;
}

export interface CreateBroadcastRequest {
    broadcastCreateInput: BroadcastCreateInput;
}

export interface GetBroadcastRequest {
    broadcastId: string;
}

export interface PauseBroadcastRequest {
    broadcastId: string;
}

export interface ResumeBroadcastRequest {
    broadcastId: string;
}

export interface UpdateBroadcastRequest {
    broadcastId: string;
    broadcastUpdateInput: BroadcastUpdateInput;
}

/**
 * 
 */
export class BroadcastsApi extends runtime.BaseAPI {

    /**
     * Creates request options for cancelBroadcast without sending the request
     */
    async cancelBroadcastRequestOpts(requestParameters: CancelBroadcastRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['broadcastId'] == null) {
            throw new runtime.RequiredError(
                'broadcastId',
                'Required parameter "broadcastId" was null or undefined when calling cancelBroadcast().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/broadcasts/{broadcastId}/cancel`;
        urlPath = urlPath.replace('{broadcastId}', encodeURIComponent(String(requestParameters['broadcastId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Pending recipients are marked cancelled and cannot be claimed.
     * Cancel a broadcast
     */
    async cancelBroadcastRaw(requestParameters: CancelBroadcastRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BroadcastEnvelope>> {
        const requestOptions = await this.cancelBroadcastRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Pending recipients are marked cancelled and cannot be claimed.
     * Cancel a broadcast
     */
    async cancelBroadcast(requestParameters: CancelBroadcastRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BroadcastEnvelope> {
        const response = await this.cancelBroadcastRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createBroadcast without sending the request
     */
    async createBroadcastRequestOpts(requestParameters: CreateBroadcastRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['broadcastCreateInput'] == null) {
            throw new runtime.RequiredError(
                'broadcastCreateInput',
                'Required parameter "broadcastCreateInput" was null or undefined when calling createBroadcast().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/broadcasts`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['broadcastCreateInput'],
        };
    }

    /**
     * Snapshots one stored template and the audience\'s active contacts, then queues immediately or at scheduled_for. Responses never include contact addresses or rendered bodies.
     * Create one broadcast
     */
    async createBroadcastRaw(requestParameters: CreateBroadcastRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BroadcastEnvelope>> {
        const requestOptions = await this.createBroadcastRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Snapshots one stored template and the audience\'s active contacts, then queues immediately or at scheduled_for. Responses never include contact addresses or rendered bodies.
     * Create one broadcast
     */
    async createBroadcast(requestParameters: CreateBroadcastRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BroadcastEnvelope> {
        const response = await this.createBroadcastRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getBroadcast without sending the request
     */
    async getBroadcastRequestOpts(requestParameters: GetBroadcastRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['broadcastId'] == null) {
            throw new runtime.RequiredError(
                'broadcastId',
                'Required parameter "broadcastId" was null or undefined when calling getBroadcast().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/broadcasts/{broadcastId}`;
        urlPath = urlPath.replace('{broadcastId}', encodeURIComponent(String(requestParameters['broadcastId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get one broadcast
     */
    async getBroadcastRaw(requestParameters: GetBroadcastRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BroadcastEnvelope>> {
        const requestOptions = await this.getBroadcastRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get one broadcast
     */
    async getBroadcast(requestParameters: GetBroadcastRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BroadcastEnvelope> {
        const response = await this.getBroadcastRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listBroadcasts without sending the request
     */
    async listBroadcastsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/broadcasts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List broadcasts
     */
    async listBroadcastsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BroadcastListEnvelope>> {
        const requestOptions = await this.listBroadcastsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * List broadcasts
     */
    async listBroadcasts(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BroadcastListEnvelope> {
        const response = await this.listBroadcastsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for pauseBroadcast without sending the request
     */
    async pauseBroadcastRequestOpts(requestParameters: PauseBroadcastRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['broadcastId'] == null) {
            throw new runtime.RequiredError(
                'broadcastId',
                'Required parameter "broadcastId" was null or undefined when calling pauseBroadcast().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/broadcasts/{broadcastId}/pause`;
        urlPath = urlPath.replace('{broadcastId}', encodeURIComponent(String(requestParameters['broadcastId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Pause a running broadcast
     */
    async pauseBroadcastRaw(requestParameters: PauseBroadcastRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BroadcastEnvelope>> {
        const requestOptions = await this.pauseBroadcastRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Pause a running broadcast
     */
    async pauseBroadcast(requestParameters: PauseBroadcastRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BroadcastEnvelope> {
        const response = await this.pauseBroadcastRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for resumeBroadcast without sending the request
     */
    async resumeBroadcastRequestOpts(requestParameters: ResumeBroadcastRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['broadcastId'] == null) {
            throw new runtime.RequiredError(
                'broadcastId',
                'Required parameter "broadcastId" was null or undefined when calling resumeBroadcast().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/broadcasts/{broadcastId}/resume`;
        urlPath = urlPath.replace('{broadcastId}', encodeURIComponent(String(requestParameters['broadcastId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Resume a paused broadcast
     */
    async resumeBroadcastRaw(requestParameters: ResumeBroadcastRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BroadcastEnvelope>> {
        const requestOptions = await this.resumeBroadcastRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Resume a paused broadcast
     */
    async resumeBroadcast(requestParameters: ResumeBroadcastRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BroadcastEnvelope> {
        const response = await this.resumeBroadcastRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateBroadcast without sending the request
     */
    async updateBroadcastRequestOpts(requestParameters: UpdateBroadcastRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['broadcastId'] == null) {
            throw new runtime.RequiredError(
                'broadcastId',
                'Required parameter "broadcastId" was null or undefined when calling updateBroadcast().'
            );
        }

        if (requestParameters['broadcastUpdateInput'] == null) {
            throw new runtime.RequiredError(
                'broadcastUpdateInput',
                'Required parameter "broadcastUpdateInput" was null or undefined when calling updateBroadcast().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/broadcasts/{broadcastId}`;
        urlPath = urlPath.replace('{broadcastId}', encodeURIComponent(String(requestParameters['broadcastId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['broadcastUpdateInput'],
        };
    }

    /**
     * Only a still-scheduled broadcast can change audience, template, subject, HTML, sender, or schedule. Changing audience or template replaces the frozen snapshot.
     * Update a scheduled broadcast
     */
    async updateBroadcastRaw(requestParameters: UpdateBroadcastRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BroadcastEnvelope>> {
        const requestOptions = await this.updateBroadcastRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Only a still-scheduled broadcast can change audience, template, subject, HTML, sender, or schedule. Changing audience or template replaces the frozen snapshot.
     * Update a scheduled broadcast
     */
    async updateBroadcast(requestParameters: UpdateBroadcastRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BroadcastEnvelope> {
        const response = await this.updateBroadcastRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
