/* tslint:disable */
/* eslint-disable */
/**
 * PaperBoy HTTP API
 * Tenant-bound transactional email API. API keys select one organization and one live or test environment. Stored instants and HTTP timestamps are RFC 3339 UTC. The queue is provider-neutral: self-hosted SMTP and Cloudflare Email Service and Amazon SES use the same messages, limits, suppressions, and event model. The signed-in console renders this contract at `/app/docs`. The Rust CLI in `crates/paperboy` calls the same bearer-key routes.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    Email,
    EmailBatchEnvelope,
    ErrorEnvelope,
    QueuedEmail,
    RateLimitErrorEnvelope,
    SendEmailInput,
} from '../models/index';

export interface GetEmailRequest {
    emailId: string;
}

export interface SendEmailRequest {
    sendEmailInput: SendEmailInput;
    idempotencyKey?: string;
}

export interface SendEmailBatchRequest {
    sendEmailInput: Array<SendEmailInput>;
}

/**
 * 
 */
export class EmailsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getEmail without sending the request
     */
    async getEmailRequestOpts(requestParameters: GetEmailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['emailId'] == null) {
            throw new runtime.RequiredError(
                'emailId',
                'Required parameter "emailId" was null or undefined when calling getEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/emails/{emailId}`;
        urlPath = urlPath.replace('{emailId}', encodeURIComponent(String(requestParameters['emailId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns one message from the organization and environment selected by the bearer key. Attachment metadata is safe; stored bytes, hashes, and storage keys are never returned.
     * Get one email
     */
    async getEmailRaw(requestParameters: GetEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Email>> {
        const requestOptions = await this.getEmailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns one message from the organization and environment selected by the bearer key. Attachment metadata is safe; stored bytes, hashes, and storage keys are never returned.
     * Get one email
     */
    async getEmail(requestParameters: GetEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Email> {
        const response = await this.getEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendEmail without sending the request
     */
    async sendEmailRequestOpts(requestParameters: SendEmailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sendEmailInput'] == null) {
            throw new runtime.RequiredError(
                'sendEmailInput',
                'Required parameter "sendEmailInput" was null or undefined when calling sendEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/emails`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['sendEmailInput'],
        };
    }

    /**
     * Validates and stores one provider-neutral message. Test keys always use the isolated test sink. Live keys require a verified organization domain, active DKIM state, and configured credentials for the resolved organization default or domain override. Provider choice is snapshotted on the queued message. Cloudflare Email Service remains responsible for provider-owned DKIM and ARC signatures. Idempotency may be supplied in the header or JSON body and is active for 24 hours per API key.
     * Queue one email
     */
    async sendEmailRaw(requestParameters: SendEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QueuedEmail>> {
        const requestOptions = await this.sendEmailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Validates and stores one provider-neutral message. Test keys always use the isolated test sink. Live keys require a verified organization domain, active DKIM state, and configured credentials for the resolved organization default or domain override. Provider choice is snapshotted on the queued message. Cloudflare Email Service remains responsible for provider-owned DKIM and ARC signatures. Idempotency may be supplied in the header or JSON body and is active for 24 hours per API key.
     * Queue one email
     */
    async sendEmail(requestParameters: SendEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QueuedEmail> {
        const response = await this.sendEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendEmailBatch without sending the request
     */
    async sendEmailBatchRequestOpts(requestParameters: SendEmailBatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['sendEmailInput'] == null) {
            throw new runtime.RequiredError(
                'sendEmailInput',
                'Required parameter "sendEmailInput" was null or undefined when calling sendEmailBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/emails/batch`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['sendEmailInput'],
        };
    }

    /**
     * Accepts a JSON array of 1 to 100 send objects. Each item is validated independently. A fully valid batch returns 200. Mixed success returns 207 and keeps accepted neighbors. An entirely rate-limited batch returns 429. Attachments and Idempotency-Key are not supported on this route.
     * Queue one to 100 emails
     */
    async sendEmailBatchRaw(requestParameters: SendEmailBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailBatchEnvelope>> {
        const requestOptions = await this.sendEmailBatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Accepts a JSON array of 1 to 100 send objects. Each item is validated independently. A fully valid batch returns 200. Mixed success returns 207 and keeps accepted neighbors. An entirely rate-limited batch returns 429. Attachments and Idempotency-Key are not supported on this route.
     * Queue one to 100 emails
     */
    async sendEmailBatch(requestParameters: SendEmailBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailBatchEnvelope> {
        const response = await this.sendEmailBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
