/* tslint:disable */
/* eslint-disable */
/**
 * PaperBoy HTTP API
 * Tenant-bound transactional email API. API keys select one organization and one live or test environment. Stored instants and HTTP timestamps are RFC 3339 UTC. The queue is provider-neutral: self-hosted SMTP and Cloudflare Email Service and Amazon SES use the same messages, limits, suppressions, and event model. The signed-in console renders this contract at `/app/docs`. The Rust CLI in `crates/paperboy` calls the same bearer-key routes.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    ErrorEnvelope,
    ListEmailEvents200Response,
} from '../models/index';

export interface ListEmailEventsRequest {
    emailId: string;
}

/**
 * 
 */
export class EventsApi extends runtime.BaseAPI {

    /**
     * Creates request options for listEmailEvents without sending the request
     */
    async listEmailEventsRequestOpts(requestParameters: ListEmailEventsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['emailId'] == null) {
            throw new runtime.RequiredError(
                'emailId',
                'Required parameter "emailId" was null or undefined when calling listEmailEvents().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/emails/{emailId}/events`;
        urlPath = urlPath.replace('{emailId}', encodeURIComponent(String(requestParameters['emailId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the stable UTC lifecycle ordered by creation instant and an internal sequence. The internal sequence is not exposed.
     * List one email\'s events
     */
    async listEmailEventsRaw(requestParameters: ListEmailEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListEmailEvents200Response>> {
        const requestOptions = await this.listEmailEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns the stable UTC lifecycle ordered by creation instant and an internal sequence. The internal sequence is not exposed.
     * List one email\'s events
     */
    async listEmailEvents(requestParameters: ListEmailEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListEmailEvents200Response> {
        const response = await this.listEmailEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
