/* tslint:disable */
/* eslint-disable */
/**
 * PaperBoy HTTP API
 * Tenant-bound transactional email API. API keys select one organization and one live or test environment. Stored instants and HTTP timestamps are RFC 3339 UTC. The queue is provider-neutral: self-hosted SMTP and Cloudflare Email Service and Amazon SES use the same messages, limits, suppressions, and event model. The signed-in console renders this contract at `/app/docs`. The Rust CLI in `crates/paperboy` calls the same bearer-key routes.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    AwsSnsEnvelope,
    ErrorEnvelope,
    OutboundProviderEventEnvelope,
    OutboundProviderSettings,
    OutboundProviderTestInput,
    OutboundProviderTestResult,
    OutboundProviderUpdateInput,
} from '../models/index';

export interface IngestAwsSesEventRequest {
    requestBody: { [key: string]: any; };
}

export interface ReceiveAwsSesSnsEventRequest {
    orgId: string;
    awsSnsEnvelope: AwsSnsEnvelope;
}

export interface TestOutboundProviderRequest {
    outboundProviderTestInput: OutboundProviderTestInput;
}

export interface UpdateOutboundProvidersRequest {
    outboundProviderUpdateInput: OutboundProviderUpdateInput;
}

/**
 * 
 */
export class OutboundProvidersApi extends runtime.BaseAPI {

    /**
     * Creates request options for getOutboundProviders without sending the request
     */
    async getOutboundProvidersRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/providers`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the organization default, each tenant-owned domain\'s effective route, provider capabilities, and safe readiness state. Credentials and provider payloads are never returned. Timestamps are UTC.
     * Read outbound-provider routing
     */
    async getOutboundProvidersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OutboundProviderSettings>> {
        const requestOptions = await this.getOutboundProvidersRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns the organization default, each tenant-owned domain\'s effective route, provider capabilities, and safe readiness state. Credentials and provider payloads are never returned. Timestamps are UTC.
     * Read outbound-provider routing
     */
    async getOutboundProviders(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OutboundProviderSettings> {
        const response = await this.getOutboundProvidersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ingestAwsSesEvent without sending the request
     */
    async ingestAwsSesEventRequestOpts(requestParameters: IngestAwsSesEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling ingestAwsSesEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/providers/aws-ses/events`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        };
    }

    /**
     * Owners and admins ingest one bounded SES SNS notification or EventBridge event through the organization-bound API key. PaperBoy verifies message correlation, stores only safe event metadata, updates hard-bounce or complaint suppressions, and replays the same provider event idempotently.
     * Ingest one Amazon SES event
     */
    async ingestAwsSesEventRaw(requestParameters: IngestAwsSesEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OutboundProviderEventEnvelope>> {
        const requestOptions = await this.ingestAwsSesEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Owners and admins ingest one bounded SES SNS notification or EventBridge event through the organization-bound API key. PaperBoy verifies message correlation, stores only safe event metadata, updates hard-bounce or complaint suppressions, and replays the same provider event idempotently.
     * Ingest one Amazon SES event
     */
    async ingestAwsSesEvent(requestParameters: IngestAwsSesEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OutboundProviderEventEnvelope> {
        const response = await this.ingestAwsSesEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for receiveAwsSesSnsEvent without sending the request
     */
    async receiveAwsSesSnsEventRequestOpts(requestParameters: ReceiveAwsSesSnsEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling receiveAwsSesSnsEvent().'
            );
        }

        if (requestParameters['awsSnsEnvelope'] == null) {
            throw new runtime.RequiredError(
                'awsSnsEnvelope',
                'Required parameter "awsSnsEnvelope" was null or undefined when calling receiveAwsSesSnsEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/api/v1/providers/aws-ses/events/{orgId}`;
        urlPath = urlPath.replace('{orgId}', encodeURIComponent(String(requestParameters['orgId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['awsSnsEnvelope'],
        };
    }

    /**
     * Public Amazon SNS subscription endpoint. PaperBoy requires the exact per-organization topic ARN, verifies the AWS certificate and SNS signature before ingestion, and automatically handles signed subscription confirmation. Configure SNS signature version 2.
     * Receive one signed Amazon SNS notification
     */
    async receiveAwsSesSnsEventRaw(requestParameters: ReceiveAwsSesSnsEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.receiveAwsSesSnsEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Public Amazon SNS subscription endpoint. PaperBoy requires the exact per-organization topic ARN, verifies the AWS certificate and SNS signature before ingestion, and automatically handles signed subscription confirmation. Configure SNS signature version 2.
     * Receive one signed Amazon SNS notification
     */
    async receiveAwsSesSnsEvent(requestParameters: ReceiveAwsSesSnsEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.receiveAwsSesSnsEventRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for testOutboundProvider without sending the request
     */
    async testOutboundProviderRequestOpts(requestParameters: TestOutboundProviderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['outboundProviderTestInput'] == null) {
            throw new runtime.RequiredError(
                'outboundProviderTestInput',
                'Required parameter "outboundProviderTestInput" was null or undefined when calling testOutboundProvider().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/providers/test`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['outboundProviderTestInput'],
        };
    }

    /**
     * Owners and admins perform a connection test with operator-injected credentials. The request never accepts a credential or secret reference.
     * Test one outbound provider
     */
    async testOutboundProviderRaw(requestParameters: TestOutboundProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OutboundProviderTestResult>> {
        const requestOptions = await this.testOutboundProviderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Owners and admins perform a connection test with operator-injected credentials. The request never accepts a credential or secret reference.
     * Test one outbound provider
     */
    async testOutboundProvider(requestParameters: TestOutboundProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OutboundProviderTestResult> {
        const response = await this.testOutboundProviderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateOutboundProviders without sending the request
     */
    async updateOutboundProvidersRequestOpts(requestParameters: UpdateOutboundProvidersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['outboundProviderUpdateInput'] == null) {
            throw new runtime.RequiredError(
                'outboundProviderUpdateInput',
                'Required parameter "outboundProviderUpdateInput" was null or undefined when calling updateOutboundProviders().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/providers`;

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['outboundProviderUpdateInput'],
        };
    }

    /**
     * Owners and admins select the organization default, one or more sending- domain overrides, or both. Existing messages retain their snapshotted provider. Selecting an unavailable adapter never falls back to SMTP.
     * Update outbound-provider routing
     */
    async updateOutboundProvidersRaw(requestParameters: UpdateOutboundProvidersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OutboundProviderSettings>> {
        const requestOptions = await this.updateOutboundProvidersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Owners and admins select the organization default, one or more sending- domain overrides, or both. Existing messages retain their snapshotted provider. Selecting an unavailable adapter never falls back to SMTP.
     * Update outbound-provider routing
     */
    async updateOutboundProviders(requestParameters: UpdateOutboundProvidersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OutboundProviderSettings> {
        const response = await this.updateOutboundProvidersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
