/* tslint:disable */
/* eslint-disable */
/**
 * PaperBoy HTTP API
 * Tenant-bound transactional email API. API keys select one organization and one live or test environment. Stored instants and HTTP timestamps are RFC 3339 UTC. The queue is provider-neutral: self-hosted SMTP and Cloudflare Email Service and Amazon SES use the same messages, limits, suppressions, and event model. The signed-in console renders this contract at `/app/docs`. The Rust CLI in `crates/paperboy` calls the same bearer-key routes.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
    DeletedResource,
    ErrorEnvelope,
    Suppression,
    SuppressionInput,
    SuppressionListEnvelope,
    SuppressionReason,
    SuppressionUpdateInput,
} from '../models/index';

export interface CreateSuppressionRequest {
    suppressionInput: SuppressionInput;
}

export interface DeleteSuppressionRequest {
    suppressionId: string;
}

export interface GetSuppressionRequest {
    suppressionId: string;
}

export interface ImportSuppressionsRequest {
    body: string;
}

export interface ListSuppressionsRequest {
    query?: string;
    reason?: SuppressionReason;
    limit?: number;
}

export interface UpdateSuppressionRequest {
    suppressionId: string;
    suppressionUpdateInput: SuppressionUpdateInput;
}

/**
 * 
 */
export class SuppressionsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createSuppression without sending the request
     */
    async createSuppressionRequestOpts(requestParameters: CreateSuppressionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['suppressionInput'] == null) {
            throw new runtime.RequiredError(
                'suppressionInput',
                'Required parameter "suppressionInput" was null or undefined when calling createSuppression().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/suppressions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['suppressionInput'],
        };
    }

    /**
     * Create one suppression
     */
    async createSuppressionRaw(requestParameters: CreateSuppressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Suppression>> {
        const requestOptions = await this.createSuppressionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Create one suppression
     */
    async createSuppression(requestParameters: CreateSuppressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Suppression> {
        const response = await this.createSuppressionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteSuppression without sending the request
     */
    async deleteSuppressionRequestOpts(requestParameters: DeleteSuppressionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['suppressionId'] == null) {
            throw new runtime.RequiredError(
                'suppressionId',
                'Required parameter "suppressionId" was null or undefined when calling deleteSuppression().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/suppressions/{suppressionId}`;
        urlPath = urlPath.replace('{suppressionId}', encodeURIComponent(String(requestParameters['suppressionId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete one suppression
     */
    async deleteSuppressionRaw(requestParameters: DeleteSuppressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeletedResource>> {
        const requestOptions = await this.deleteSuppressionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Delete one suppression
     */
    async deleteSuppression(requestParameters: DeleteSuppressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeletedResource> {
        const response = await this.deleteSuppressionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSuppression without sending the request
     */
    async getSuppressionRequestOpts(requestParameters: GetSuppressionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['suppressionId'] == null) {
            throw new runtime.RequiredError(
                'suppressionId',
                'Required parameter "suppressionId" was null or undefined when calling getSuppression().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/suppressions/{suppressionId}`;
        urlPath = urlPath.replace('{suppressionId}', encodeURIComponent(String(requestParameters['suppressionId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get one suppression
     */
    async getSuppressionRaw(requestParameters: GetSuppressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Suppression>> {
        const requestOptions = await this.getSuppressionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Get one suppression
     */
    async getSuppression(requestParameters: GetSuppressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Suppression> {
        const response = await this.getSuppressionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for importSuppressions without sending the request
     */
    async importSuppressionsRequestOpts(requestParameters: ImportSuppressionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling importSuppressions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/csv';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/suppressions/import`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * UTF-8 CSV bounded to 1 MiB and 5,000 rows. The complete file validates before mutation. Duplicate emails keep the strongest reason.
     * Import suppressions from CSV
     */
    async importSuppressionsRaw(requestParameters: ImportSuppressionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.importSuppressionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * UTF-8 CSV bounded to 1 MiB and 5,000 rows. The complete file validates before mutation. Duplicate emails keep the strongest reason.
     * Import suppressions from CSV
     */
    async importSuppressions(requestParameters: ImportSuppressionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.importSuppressionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSuppressions without sending the request
     */
    async listSuppressionsRequestOpts(requestParameters: ListSuppressionsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['reason'] != null) {
            queryParameters['reason'] = requestParameters['reason'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/suppressions`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List suppressions
     */
    async listSuppressionsRaw(requestParameters: ListSuppressionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SuppressionListEnvelope>> {
        const requestOptions = await this.listSuppressionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * List suppressions
     */
    async listSuppressions(requestParameters: ListSuppressionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SuppressionListEnvelope> {
        const response = await this.listSuppressionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateSuppression without sending the request
     */
    async updateSuppressionRequestOpts(requestParameters: UpdateSuppressionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['suppressionId'] == null) {
            throw new runtime.RequiredError(
                'suppressionId',
                'Required parameter "suppressionId" was null or undefined when calling updateSuppression().'
            );
        }

        if (requestParameters['suppressionUpdateInput'] == null) {
            throw new runtime.RequiredError(
                'suppressionUpdateInput',
                'Required parameter "suppressionUpdateInput" was null or undefined when calling updateSuppression().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/suppressions/{suppressionId}`;
        urlPath = urlPath.replace('{suppressionId}', encodeURIComponent(String(requestParameters['suppressionId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['suppressionUpdateInput'],
        };
    }

    /**
     * Update one suppression
     */
    async updateSuppressionRaw(requestParameters: UpdateSuppressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Suppression>> {
        const requestOptions = await this.updateSuppressionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Update one suppression
     */
    async updateSuppression(requestParameters: UpdateSuppressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Suppression> {
        const response = await this.updateSuppressionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
